### PR TITLE
Add /kick command and remove botan support

### PR DESCRIPTION
**Pull request by Jerry981028**

### CODE REVIEW

**Comment by jh0ker** [comment]
Looks nice. I was wondering, perhaps it would be helpful if you could kick a player by replying to one of the messages of the player you want to kick. The bot should be able to see the messages that are sent `via @thebot`, even with privacy mode enabled, so you could get the ID from that. What do you think?

**Comment by Jerry981028** [comment]
That's a good idea. It's much more convenient to kick a specific person by replying.

**Comment by jh0ker** [comment]
I think I want to merge #44 first, you will probably have to do a manual merge after that. Sorry about that :/

**Comment by Jerry981028** [comment]
No problem, but I'm currently a little busy, and the new function is not very stable now.

**Comment by jh0ker** [comment]
@Jerry981028 Alright 👍

**Comment by Jerry981028** [comment]
#44 is merged. I'll manually merge these things in a couple of days.

**Comment by Jerry981028** [comment]
Ok, it's able to merge.

**Comment by Jerry981028** [comment]
Since botan is deleted in this [https://github.com/python-telegram-bot/python-telegram-bot/pull/776/commits/502b99b70ca1a06981a3e0c016d234d298b4a8d3](commit), is it still necessary to keep it in the bot?

**Comment by jh0ker** [comment]
I think we can drop botan support completely.

**Comment by Jerry981028** [comment]
Ok, I'll delete those codes.

**Comment by Jerry981028** [comment]
Deleted.
It works normally in a short test.

**Comment by jh0ker** [comment]
Nice, thanks for the config rework as well 👍 You think this is good to merge? Looks good to me

**Comment by Jerry981028** [comment]
Tested. It's well-prepared to merge.

**Comment by jh0ker** [comment]
Thanks again for your contribution!

**Comment by Jerry981028** [comment]
My pleasure.

**Comment by jh0ker** [comment]
Changes are live 🚀

**Comment by Jerry981028** [comment]
Maybe the command list of @unobot should be updated.
Here's mine
`new - Start a new game
join - Join the current game
start - Start the game
leave - Leave the game you're in
close - Close the game lobby
open - Open the game lobby
kill - Terminate the game
kick - Kick players out of the game
enable_translations - Enable multi-translations
disable_translations - Disable multi-translations
skip - Skip the current player
notify_me - Get a message when there's a new game in this group
help - How to use this bot?
settings - Language and other settings
stats - Show statistics
source - See source information
news - All news about this bot
modes - Explanation of game modes`

**Comment by jh0ker** [comment]
Thanks, I updated the command list. I only moved the `modes` command under `help` where I had it before

**Comment by Jerry981028** [comment]
Thanks.

**Pull request merged**
